package com.composeventure.compose_cinematic;

public class HtmlContent {
    public static String getHtml() {
        return "<!DOCTYPE html>"
        + "<html lang=\"en\">"
        + "<head>"
        + "<meta charset=\"UTF-8\">"
        + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        + "<script src=\"file:///android_res/raw/functions.js\" defer></script>"   
        + "<title>Compose-Native</title>"
        + "<style>"
        + "body {"
        + "    color: #ffffff;"
        + "    background: #000000;"
        + "}"
        + ".body {"
        + "    position: fixed;"
        + "    left: 0;"
        + "    right: 0;"
        + "    top: 0;"
        + "    bottom: 0;"
        + "    overflow: hidden;"
        + "    text-align: center;"
        + "    font-size: 20px;"
        + "    font-family: sans-serif;"
        + "    width: 100%;"
        + "    height: 100%;"
        + "    margin: auto;"
        + "    padding: auto;"
        + "}"
        + ".UpdateImage {"
        + "    position: relative;"
        + "    width: 30%;"
        + "    height: auto;"
        + "    margin: auto;"
        + "    margin-top: 3rem;"
        + "    background: #dcdcdc10;"
        + "    padding: 20%;"
        + "    border-radius: 100%;"
        + "}"
        + ".LoadingIconer {"
        + "    position: relative;"
        + "    width: 25px;"
        + "    height: 25px;"
        + "    background: transparent;"
        + "    border-radius: 100px;"
        + "    padding: 10%;"
        + "    margin: auto;"
        + "    box-shadow: 0.5px 1px 0.5px 0.5px #dcdcdc80;"
        + "    animation: spin 1s linear infinite reverse;"
        + "}"
        + "@keyframes spin {"
        + "    0% { transform: rotate(0deg); }"
        + "    100% { transform: rotate(-360deg); }"
        + "}"
        + "</style>"
        + "</head>"
        + "<body>"
        + "</body>"
        + "</html>";
    }
}
